package com.macmie.mfoodyex.JWTHelper;

import com.google.gson.Gson;
import com.macmie.mfoodyex.JWTSpringSecurity.CustomUserDetailsService;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.User;
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource;
import org.springframework.util.StringUtils;
import org.springframework.web.filter.OncePerRequestFilter;

import javax.servlet.FilterChain;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.io.IOException;

@Slf4j
public class JWTAuthenticationFilter extends OncePerRequestFilter {

    @Autowired
    JWTProvider jwtProvider;

    @Autowired
    AuthenticationManager authenticationManager;

    @Autowired
    CustomUserDetailsService customUserDetailsService;

    private Gson gson = new Gson();

    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain)
            throws ServletException, IOException {
        String token = getJWTToken(request);
        log.info("--- JWTAuthenticationFilter: Start");
        // Check if Token is valid (generated by this Project)
        if(jwtProvider.validationToken(token)){
            log.info("--- JWTAuthenticationFilter: Check Token");
            // Valid Token
            String jsonDataUserName = jwtProvider.decodeToken(token); // get data (userName) in the valid Token
            User userDetail = (User) customUserDetailsService.loadUserByUsername(jsonDataUserName); // query to get User by userName from DB
            log.info("UserName: " + jsonDataUserName);

            // Authenticate Token
            UsernamePasswordAuthenticationToken authenticationTokenDecode =
                    new UsernamePasswordAuthenticationToken(userDetail, null, userDetail.getAuthorities());

            authenticationTokenDecode.setDetails(new WebAuthenticationDetailsSource().buildDetails(request));
            // Authentication authentication = authenticationManager.authenticate(authenticationTokenDecode);
            SecurityContextHolder.getContext().setAuthentication(authenticationTokenDecode);
        }

        log.info("--- JWTAuthenticationFilter: End");
        // Continue to the URLs
        filterChain.doFilter(request, response);
    }

    private String getJWTToken(HttpServletRequest request){
        // Get Token from User's request
        String authenticationTokenHeader = request.getHeader("Authorization");
        if(StringUtils.hasText(authenticationTokenHeader) && authenticationTokenHeader.contains("Bearer")){
            String token = authenticationTokenHeader.substring(7); // remove "Bearer " and get Token
            return token;
        }
        return null;
    }
}
